/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const IconData noun_heart_6151 = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData noun_home_1315561 = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData noun_search_2475045 = IconData(0xe802, fontFamily: _kFontFam);
}
